// <auto-generated />
namespace DemoIdentityT2012EManual.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class InitDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202203101137584_InitDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
